# This file generates the GitHub Actions matrix
# For simple board + shield combinations, add them
# to the top level board and shield arrays, for more
# control, add individual board + shield combinations to
# the `include` property, e.g:
#
# board: [ "nice_nano_v2" ]
# shield: [ "corne_left", "corne_right" ]
# include:
#   - board: bdn9_rev2
#   - board: nice_nano_v2
#     shield: reviung41
#
---
include:
  - board: nice_nano_v2
    shield: xavien_left nice_view  
  - board: nice_nano_v2
    shield: xavien_right nice_view  
  - board: nice_nano_v2
    shield: xavien_dongle
    snippet: studio-rpc-usb-uart
  - board: seeeduino_xiao_ble
    shield: xavien_dongle_xiao
    snippet: studio-rpc-usb-uart
  - board: nice_nano_v2
    shield: xavien_left-master nice_view  
    snippet: studio-rpc-usb-uart
  - board: nice_nano_v2
    shield: xavien_right-master nice_view  
    snippet: studio-rpc-usb-uart
  - board: nice_nano_v2
    shield: settings_reset
  - board: seeeduino_xiao_ble
    shield: settings_reset
  

